<li>
              <div class="pro_list">
                <div class="pro_img"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:arcurl/]"></a></div>
                <div class="pro_title">
                  <div class="pro_left"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></div>
                  <div class="pro_right"><span class="anum_6"><script src="{dede:field name='phpurl'/}/count.php?view=yes&aid={dede:field name='id'/}&mid={dede:field name='mid'/}"type='text/javascript' language="javascript"></script></span></div>
                </div>
              </div>