<?php
$z[0]=Array("flink","\r\n          [field:link /]\r\n            ",138,237);
$z[0][4]['titlelen']="24";
$z[0][4]['row']="4";
$z[0][4]['type']="text";
$z[1]=Array("channel","\r\n        <li>|<a href='[field:typelink/]'>[field:typename/]</a></li>\r\n        ",509,630);
$z[1][4]['type']="top";
$z[2]=Array("global","",711,737);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",759,784);
$z[3][4]['name']="cfg_tbdhhm";
$z[4]=Array("global","",794,816);
$z[4][4]['name']="cfg_chz";
$z[5]=Array("global","",825,846);
$z[5][4]['name']="cfg_dz";

?>