<?php
$z[0]=Array("global","",81,105);
$z[0][4]['name']="cfg_tbhyy";
$z[1]=Array("global","",1218,1245);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1254,1282);
$z[2][4]['name']="cfg_indexname";
$z[3]=Array("global","",1323,1349);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1402,1427);
$z[4][4]['name']="cfg_tbdhhm";
$z[5]=Array("global","",1593,1618);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("field","(@me==\"\")? @me=\" class='current' \":@me=\"\";",1621,1713);
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[7]=Array("channelartlist"," \r\n<li>\r\n <b><a href=\"{dede:field name='typeurl'/}\" {dede:field name='currentstyle'/}>{dede:field name='typename'/}</a></b>\r\n <ul class=\"fixfloat\">\r\n {dede:channel type='son' noself='yes'}\r\n <li><a href=\"[field:typelink/]\">[field:typename/]</a></li> {/dede:channel} </ul></li> ",1744,2078);
$z[7][4]['typeid']="top";

?>