<?php
$z[0]=Array("global","",620,646);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",690,720);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",757,784);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1678,1713);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n          <div class=\"left_con\">\r\n            <div class=\"type_list\">\r\n              <ul>\r\n                <li class='first_cat'><a href='[field:typelink/]' title='[field:typename/]'>[field:typename/]</a></li>\r\n              </ul>\r\n            </div>\r\n          </div>\r\n          ",1972,2322);
$z[4][4]['reid']="15";
$z[4][4]['type']="son";
$z[4][4]['typeid']="15";
$z[5]=Array("type","\r\n          <div class=\"home_top\"><h3>[field:typename /]</h3><span><a href=\"[field:typelink /]\">更多>></a></span></div>",2436,2600);
$z[5][4]['typeid']="15";
$z[5][4]['row']="1";
$z[6]=Array("arclist","\r\n                <div class=\"pro_list\">\r\n                 \r\n                  <div class=\"pro_img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:arcurl/]\"></a></div><div class=\"pro_title\"><div class=\"pro_left\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div><div class=\"pro_right\">[field:click/]</div></div></div>\r\n           ",2725,3171);
$z[6][4]['row']="18";
$z[6][4]['typeid']="15";
$z[7]=Array("arclist","\r\n            <li>\r\n              <div class=\"pro_list\">\r\n                <div class=\"pro_img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:arcurl/]\"></a></div>\r\n                <div class=\"pro_title\">\r\n                  <div class=\"pro_left\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n                  <div class=\"pro_right\"><span class=\"anum_6\"><script src=\"{dede:field name='phpurl'/}/count.php?view=yes&aid={dede:field name='id'/}&mid={dede:field name='mid'/}\"type='text/javascript' language=\"javascript\"></script></span></div>\r\n                </div>\r\n              </div>\r\n             ",3550,4260);
$z[7][4]['typeid']="6";
$z[8]=Array("type","</h3>\r\n          <i>About Us</i><span><a href=\"[field:typelink/]\">更多>></a>",4485,4598);
$z[8][4]['typeid']="22";
$z[9]=Array("type","</h3>\r\n          <i>News</i><span><a href=\"[field:typelink/]\">更多>></a>",5811,5920);
$z[9][4]['typeid']="17";
$z[10]=Array("arclist","\r\n            <li><span class='time'>[field:pubdate function=\"MyDate('y-m-d',@me)\"/]</span><a href='[field:arcurl/]' title='[field:title/]'>[field:title/]</a></li>\r\n           ",5994,6238);
$z[10][4]['typeid']="17";
$z[10][4]['row']="9";
$z[10][4]['orderby']="pubdate";
$z[11]=Array("include","",6371,6408);
$z[11][4]['filename']="footer.htm";

?>