<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",993,1028);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1159,1181);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n<li class='first_cat'><a href='[field:typelink/]' title='[field:typename/]'>[field:typename/]</a></li>\r\n",1249,1397);
$z[6][4]['type']="son";
$z[7]=Array("include","",1432,1470);
$z[7][4]['filename']="service.htm";
$z[8]=Array("field","",1524,1553);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n<div class=\"articleList\">\r\n<ul>\r\n<li><span class='time'>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a href='[field:arcurl/]' alt='[field:title/]'>[field:title/]</a></li>\r\n</ul>\r\n</div>\r\n",1590,1826);
$z[9][4]['pagesize']="12";
$z[10]=Array("pagelist","",1946,2017);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",2162,2199);
$z[11][4]['filename']="footer.htm";

?>