<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",987,1022);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1152,1174);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n<li class='first_cat'><a href='[field:typelink/]' title='[field:typename/]'>[field:typename/]</a></li>\r\n",1242,1390);
$z[6][4]['type']="son";
$z[7]=Array("include","",1423,1461);
$z[7][4]['filename']="service.htm";
$z[8]=Array("field","",1517,1539);
$z[8][4]['name']="typename";
$z[9]=Array("list","\r\n<div class=\"pro_list\">\r\n<div class=\"pro_img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:arcurl/]\"></a></div><div class=\"pro_title\"><div class=\"pro_left\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div><div class=\"pro_right\">[field:click/]</div></div>\r\n\r\n</div>\r\n",1600,1972);
$z[9][4]['pagesize']="12";
$z[10]=Array("pagelist","",2038,2116);
$z[10][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",2183,2220);
$z[11][4]['filename']="footer.htm";

?>